### PR TITLE
A few syntax corrections

### PR DESCRIPTION
**Pull request by WAIC-joel**
Hey Mr. McTwist,
Long-time listener, first time caller. Couldn't help but notice the script didn't work so I fixed it.

### CODE REVIEW

**Comment by WAIC-joel** [comment]
Let me update my .git stuff to get the commit right, sorry

**Comment by codermctwist** [comment]
Hey Joel, Like the new nick? :stuck_out_tongue_winking_eye: I force push all my stuff all the time - sorry, apparently that just closes pull requests. Feel free to post the diff and I can fix it up. Thanks!

**Comment by WAIC-joel** [comment]
Yeah, the new nick threw me off, but it fits hipster Ben better than hermit Ben. I'm in Baltimore with WAIC this week and just getting everything set up to be their client developer, including the macbook they bought me :100: so that's why I was poking around this repo.

https://github.com/codermctwist/DotFiles/commit/64f0f9a63b6a652c21a742024070079d8a4ef19d should still have the diff

**Comment by codermctwist** [comment]
thanks

**Pull request closed without merging**
